build:
  install-and-lint:
    image: node:8
    environment:
      - NPM_CONFIG_CACHE=/drone/.npm
      - NPM_CONFIG_LOGLEVEL=warn
    commands:
      - npm install
      - npm run lint

  publish-on-npm:
    image: node:8
    commands:
      - echo "//registry.npmjs.org/:_authToken=$$NPM_TOKEN" >> ~/.npmrc
      - git config --global user.name "nemobot";
      - git config --global user.email "our-bots@buildo.io";
      - npm run release-version -- --token=$$GITHUB_TOKEN
    when:
      branch:
        - master

cache:
  mount:
    - /drone/.npm