build:
  install-and-lint:
    image: node:8
    environment:
      - NPM_CONFIG_CACHE=/drone/.npm
      - NPM_CONFIG_LOGLEVEL=warn
    commands:
      - npm install
      - npm run lint

  publish-on-npm:
    image: node:8
    commands:
      - echo "//registry.npmjs.org/:_authToken=$$NPM_TOKEN" >> ~/.npmrc
      - git config user.name "nemobot";
      - git config user.email "our-bots@buildo.io";
      - git branch --set-upstream-to origin/master
      - mkdir -p ~/.smooth-release
      - echo $$GITHUB_TOKEN > ~/.smooth-release/gh_token
      - DEBUG=* node node_modules/smooth-release
    when:
      branch:
        - master

cache:
  mount:
    - /drone/.npm